### ISSUE TITLE
opencv is needed

### ISSUE THREAD

**Issue by JoaoPeriquito** [openmiblab/pckg-wezel#11]
opencv is now needed to do the region growing and the gaussian filter to automatically detect the aorta region. Would it be possible to add "opencv-python" to the requirements list?

**Comment by plaresmedima** [comment]
This is not part of wezel but of the application you are writing. Should be added to the dependencies of your application (iBEAt)

**Comment by plaresmedima** [comment]
Only if we include region growing and gaussian filter in the weasel
distribution. For now it is only in iBEAt so it will have to go in the
requirements file of iBEAt.

These are useful tools to include in weasel as they have more general
applicability but run it inside iBEAT first for a while. Once you have run
it on enough data and are confident it works well, then add it to weasel as
an action and create a pull request for weasel

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*
