### ISSUE TITLE
Auto Importing (via XNAT)

### ISSUE THREAD

**Issue by JoaoPeriquito** [openmiblab/pckg-wezel#5]
Download via XNAT using "**MDRauto**" is complete, however it gives an error, when the freshly downloaded dataset is opening

"app.open(os.path.join(downloadFolder, dataset.label))" on the xnat.py script does not seem to work properly it stops on the python script called "**folder.py**" (line 61): **return self.required + self.__dict__['attributes']**

with the following error: "**TypeError: can only concatenate list (not "dict") to list**"

self.required is **['PatientID', 'StudyInstanceUID', 'SeriesInstanceUID', 'SOPInstanceUID', 'SOPClassUID', 'NumberOfFrames', 'PatientName', 'StudyDescription', 'StudyDate', 'SeriesDescription', 'SeriesNumber', 'InstanceNumber', 'AcquisitionTime']**

self.__ dict __['attributes'] is **{}**

**Comment by JoaoPeriquito** [comment]
if I say  self.__ dict __['attributes'] = []  (instead of a {}) it works, but I know where or how should I do this to minimize the impact of this change

**Comment by plaresmedima** [comment]
Hi joao,

The current version of folder.py in dbdicom does that correctly I think:

https://github.com/QIB-Sheffield/dbdicom/blob/main/dbdicom/folder.py

line 61 is:

return self.required + self.__dict__['attributes']

Maybe the dbdicom inside iBEAt is still an older version?

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by plaresmedima** [comment]
This was a bug in dbdicom - should be fixed now so please get the latest dbdicom version and try again.
